blackcoffee/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dashboard.urls")),
]

dashboard/urls.py
from django.urls import include, path

from . import views

app_name = "dashboard"

urlpatterns = [
    # path("", views.home, name="index"),
    path("likelihood/", views.likelihood, name="likelihood"),
    path("intensity/", views.intensity, name="intensity"),
    path("relevance/", views.relevance, name="relevance"),
    path("", views.industry_summary_list, name="filter"),
]

dashboard/models.py
import datetime as dt

from django.db import models
from django.utils import timezone

# Create your models here.


class IndustrySummary(models.Model):
    topic = models.CharField(max_length=75)
    region = models.CharField(max_length=75, blank=True)
    sector = models.CharField(max_length=75, blank=True)
    country = models.CharField(max_length=100, blank=True)
    pestle = models.CharField(max_length=100, blank=True)
    sources = models.CharField(max_length=100, blank=True)
    impact = models.CharField(max_length=75, blank=True)
    insight = models.CharField(max_length=200, blank=True)
    title = models.TextField(default="")
    url = models.URLField(blank=True)
    likelihood = models.IntegerField(default=0, null=True)
    relevance = models.IntegerField(default=0, null=True)
    intensity = models.IntegerField(default=0, null=True)
    start_year = models.DateField(null=True)
    end_year = models.DateField(null=True)
    add_date = models.DateTimeField(null=True)
    publish_date = models.DateTimeField(null=True)

    def __str__(self) -> str:
        title = self.title
        return title[:50]

    def _get_year(self):
        return str(self.published_date.year)

dashboard/views.py
import django_filters
from django import forms
from django.core.paginator import Paginator
from django.shortcuts import render

from .models import IndustrySummary

# Create your views here.


def likelihood(request):
    data = {
        "data": [],
        "lable1": [],
        "lable2": [],
    }
    summaries = IndustrySummary.objects.all()[:200]
    for summary in summaries:
        if summary.country or summary.region:
            data["data"].append(summary.likelihood)
            data["lable1"].append(summary.country)
            data["lable2"].append(summary.region)
    context = {
        "data": data,
        "title": "Likelihood",
        "limits": 15,
        "type1": "bar",
        "type2": "line",
    }
    return render(
        request,
        "chart-bar.html",
        context,
    )


def intensity(request):
    data = {
        "data": [],
        "lable1": [],
        "lable2": [],
    }
    summaries = IndustrySummary.objects.all()[:200]
    for summary in summaries:
        if summary.country or summary.region:
            data["data"].append(summary.intensity)
            data["lable1"].append(summary.country)
            data["lable2"].append(summary.region)
    context = {
        "data": data,
        "title": "Intensity",
        "limits": 100,
        "type1": "bar",
        "type2": "line",
    }
    return render(
        request,
        "chart-bar.html",
        context,
    )


def relevance(request):
    data = {
        "data": [],
        "lable1": [],
        "lable2": [],
    }
    summaries = IndustrySummary.objects.all()[:200]
    for summary in summaries:
        if summary.country or summary.region:
            data["data"].append(summary.relevance)
            data["lable1"].append(summary.country)
            data["lable2"].append(summary.region)
    context = {
        "data": data,
        "title": "Revelance",
        "limits": 15,
        "type1": "bar",
        "type2": "line",
    }
    return render(
        request,
        "chart-bar.html",
        context,
    )


def home(request):
    return render(
        request,
        "home.html",
    )


class IndustrySummaryFilter(django_filters.FilterSet):
    end_year = django_filters.DateFilter(
        field_name="end_year",
        lookup_expr="lte",
        widget=forms.DateInput(attrs={"class": "form-control"}),
    )
    topic = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    sector = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    region = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    pestle = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    sources = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    country = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = IndustrySummary
        fields = [
            "end_year",
            "topic",
            "sector",
            "region",
            "pestle",
            "sources",
            "country",
        ]


def industry_summary_list(request):
    filter_data = IndustrySummaryFilter(
        request.GET, queryset=IndustrySummary.objects.all()
    )
    paginator = Paginator(filter_data.qs, 25)  # Show 10 results per page

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        "filter-list.html",
        {"filter": filter_data, "page_obj": page_obj},
    )

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css"
          rel="stylesheet"/>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
            crossorigin="anonymous"></script>
  </head>
  <body class="sb-nav-fixed">
    {% include 'nav.html' %}
    <div id="layoutSidenav">
      {% include 'side-nav.html' %}
      <div id="layoutSidenav_content">
        {% block content %}{% endblock %}
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"
            crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    {% block script %}
    {% endblock script %}
  </body>
</html>

templates/chart-bar.html
{% extends 'base.html' %}
{% block content %}
  <main>
    <div class="container-fluid px-4">
      <h1 class="mt-4">Chart {{ title }} - Country</h1>
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-body">
              <canvas id="myChart"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
      <div class="d-flex align-items-center justify-content-between small">
        <div class="text-muted">Copyright &copy; Your Website 2022</div>
        <div>
          <a href="#">Privacy Policy</a>
          &middot;
          <a href="#">Terms &amp; Conditions</a>
        </div>
      </div>
    </div>
  </footer>
{% endblock content %}
{% block script %}
  <script>
      var ctx = document.getElementById("myChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: {{ data.lable1|safe}},
          datasets: [{
            lineTension: 0.3,
            backgroundColor: "rgba(2,117,216,0.2)",
            borderColor: "rgba(2,117,216,1)",
            pointRadius: 5,
            pointBackgroundColor: "rgba(2,117,216,1)",
            pointBorderColor: "rgba(255,255,255,0.8)",
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "rgba(2,117,216,1)",
            pointHitRadius: 50,
            pointBorderWidth: 2,
            data: {{data.data|safe}},
          }
          
          
          ],
        },
        options: {
          scales: {
            xAxes: [{
              gridLines: {
                display: false,
              },
              ticks: {
                min: 0,
                max:1000,
                maxTicksLimit:20
              }
            }],
            yAxes: [{
              ticks: {
                min: 0,
                max: {{limits|safe}},
                maxTicksLimit: 15
              },
              gridLines: {
                color: "rgba(0, 0, 0, .125)",
              }
            }],
          },
          legend: {
            display:false,
          }
        }
      });
  </script>
{% endblock %}

templates/filter-list.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
  <main>
    <div class="container-fluid px-4">
      <h1 class="mt-4">Dashboard</h1>
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header">Filter Data</div>
          </div>
        </div>
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header bg-danger">
              <form method="get">
                <div class="row">
                  <div class="col-md-4">
                    <p>
                      <input type="date"
                             name="end_year"
                             class="form-control"
                             id="id_end_year"
                             placeholder="End year is less than or equal to">
                    </p>
                  </div>
                  <div class="col-md-4">
                    <p>
                      <input type="text"
                             name="topic"
                             class="form-control"
                             id="id_topic"
                             placeholder="Topic contains">
                    </p>
                  </div>
                  <div class="col-md-4">
                    <p>
                      <input type="text"
                             name="sector"
                             class="form-control"
                             id="id_sector"
                             placeholder="Sector contains">
                    </p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4">
                    <p>
                      <input type="text"
                             name="region"
                             class="form-control"
                             id="id_region"
                             placeholder="Region contains">
                    </p>
                  </div>
                  <div class="col-md-4">
                    <p>
                      <input type="text"
                             name="pestle"
                             class="form-control"
                             id="id_pestle"
                             placeholder="Pestle contains">
                    </p>
                  </div>
                  <div class="col-md-4">
                    <p>
                      <input type="text"
                             name="sources"
                             class="form-control"
                             id="id_sources"
                             placeholder="Sources contains">
                    </p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4">
                    <p>
                      <input type="text"
                             name="country"
                             class="form-control"
                             id="id_country"
                             placeholder="Country contains">
                    </p>
                  </div>
                  <div class="col-md-4">
                    <!-- empty column to fill the row -->
                  </div>
                  <div class="col-md-4">
                    <!-- empty column to fill the row -->
                  </div>
                </div>
                <button class="btn btn-primary" type="submit">Filter</button>
                <a class="btn btn-danger"
                   href="?{% for key in request.GET %}{% if key != 'page' %}&{{ key }}={% endif %}{% endfor %}"
                   class="btn btn-secondary">Clear Filter</a>
              </form>
            </div>
            <div class="card-body  table-responsive">
              <table class="table table-striped  table-bordered">
                <thead>
                  <tr>
                    <th class="text-black" colspan="16">Total Result Found-{{ filter.qs.count }}</th>
                  </tr>
                  <tr>
                    <th>SR. No.</th>
                    <th>Topic</th>
                    <th>Region</th>
                    <th>Sector</th>
                    <th>Country</th>
                    <th>PESTLE</th>
                    <th>Sources</th>
                    <th>Impact</th>
                    <th>Insight</th>
                    <th>Title</th>
                    <th>Likelihood</th>
                    <th>Relevance</th>
                    <th>Intensity</th>
                    <th>Start Year</th>
                    <th>End Year</th>
                    <th>Add Date</th>
                    <th>Publish Date</th>
                  </tr>
                </thead>
                <tbody>
                  {% for summary in page_obj %}
                    <tr>
                      <td>{{ forloop.counter }}</td>
                      <td>{{ summary.topic }}</td>
                      <td>{{ summary.region }}</td>
                      <td>{{ summary.sector }}</td>
                      <td>
                        {{ summary.country }}
                      </td>
                      <td>
                        {{ summary.pestle }}
                      </td>
                      <td>
                        {{ summary.sources }}
                      </td>
                      <td>
                        {{ summary.impact }}
                      </td>
                      <td>
                        {{ summary.insight|slice:":20"  }}
                      </td>
                      <td>
                        {{ summary.title|slice:":20"  }}.....
                      </td>
                      <td>
                        {{ summary.likelihood }}
                      </td>
                      <td>
                        {{ summary.relevance }}
                      </td>
                      <td>
                        {{ summary.intensity }}
                      </td>
                      <td>
                        {{ summary.start_year|naturalday }}
                      </td>
                      <td>
                        {{ summary.end_year|naturalday }}
                      </td>
                      <td>
                        {{ summary.add_date|naturalday }}
                      </td>
                      <td>
                        {{ summary.publish_date|naturalday }}
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
                <tfoot>
                  <tr>
                    <td colspan="8">
                      <div class="pagination">
                        <span class="step-links">
                          {% if page_obj.has_previous %}
                            <a class="btn btn-danger" href="?page=1">&laquo; first</a>
                            <a class="btn btn-danger"
                               href="?page={{ page_obj.previous_page_number }}">previous</a>
                          {% endif %}
                          <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                          </span>
                          {% if page_obj.has_next %}
                            <a class="btn btn-danger" href="?page={{ page_obj.next_page_number }}">next</a>
                            <a class="btn btn-danger"
                               href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                          {% endif %}
                        </span>
                      </td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  {% endblock %}

templates/nav.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <!-- Navbar Brand -->
  <a class="navbar-brand ps-3" href="index.html">Dashboard</a>
  <!-- Sidebar Toggle -->
  <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0"
          id="sidebarToggle"
          href="#!">
    <i class="fas fa-bars"></i>
  </button>
  <!-- Navbar Search -->
  <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
    <div class="input-group">
      <input class="form-control"
             type="text"
             placeholder="Search for..."
             aria-label="Search for..."
             aria-describedby="btnNavbarSearch"/>
      <button class="btn btn-primary" id="btnNavbarSearch" type="button">
        <i class="fas fa-search"></i>
      </button>
    </div>
  </form>
  <!-- Navbar -->
  <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle"
         id="navbarDropdown"
         href="#"
         role="button"
         data-bs-toggle="dropdown"
         aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
      <ul class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdown">
        <li>
          <a class="dropdown-item" href="#!">Settings</a>
        </li>
        <li>
          <a class="dropdown-item" href="#!">Activity Log</a>
        </li>
        <li>
          <hr class="dropdown-divider" />
        </li>
        <li>
          <a class="dropdown-item" href="#!">Logout</a>
        </li>
      </ul>
    </li>
  </ul>
</nav>

templates/side-nav.html
<div id="layoutSidenav_nav">
  <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
      <div class="nav">
        <div class="sb-sidenav-menu-heading">Core</div>
        <a class="nav-link" href="index.html">
          <div class="sb-nav-link-icon">
            <i class="fas fa-tachometer-alt"></i>
          </div>
          Dashboard
        </a>
        <div class="collapse"
             id="collapseLayouts"
             aria-labelledby="headingOne"
             data-bs-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <a class="nav-link" href="layout-static.html">Static Navigation</a>
            <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
          </nav>
        </div>
        <nav class="sb-sidenav-menu-nested nav">
          <a class="nav-link" href="{% url 'dashboard:filter' %}">All Filters</a>
          <a class="nav-link" href="{% url 'dashboard:likelihood' %}">Chart-One</a>
          <a class="nav-link" href="{% url 'dashboard:relevance' %}">Chart-Two</a>
          <a class="nav-link" href="{% url 'dashboard:intensity' %}">Chart-Three</a>
        </nav>
      </div>
    </nav>
  </div>